//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.29 at 02:42:21 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:<%= props.namespace %>", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package <%= props.modelPackage %>;
